run() { echo "@@CMD@@ $1"; eval "$1" 2>&1; echo "@@END@@"; }
echo "@@SEC@@ U-01 root 계정 원격 접속 제한"
run "grep -i '^permitrootlogin' /etc/ssh/sshd_config"
run "grep -c 'pts/' /etc/securetty"
echo "@@SEC@@ U-02 패스워드 복잡성 설정"
run "grep -v '^#' /etc/security/pwquality.conf | grep -v '^\$'"
echo "@@SEC@@ U-03 계정 잠금 임계값 설정"
run "grep -h pam_faillock /etc/pam.d/sshd /etc/pam.d/common-auth"
echo "@@SEC@@ U-04 패스워드 파일 보호 / U-18 / U-19 권한"
run "ls -l /etc/passwd /etc/shadow /etc/opasswd"
echo "@@SEC@@ U-05 root 이외의 UID가 0 금지"
run "awk -F: '\$3==0 {print \$1}' /etc/passwd"
echo "@@SEC@@ U-06 root 계정 SU 제한"
run "grep -n pam_wheel /etc/pam.d/su"
run "grep -E '^wheel|^sudo' /etc/group"
echo "@@SEC@@ U-07 패스워드 최소 길이 설정"
run "grep -E 'minlen' /etc/security/pwquality.conf"
echo "@@SEC@@ U-08 패스워드 최대 사용기간 설정"
run "grep -i '^PASS_MAX_DAYS' /etc/login.defs"
run "chage -l root"
echo "@@SEC@@ U-09 패스워드 최소 사용기간 설정"
run "grep -i '^PASS_MIN_DAYS' /etc/login.defs"
echo "@@SEC@@ U-10 불필요한 계정 제거"
run "cat /etc/passwd"
echo "@@SEC@@ U-11 관리자 그룹에 최소한의 계정 포함"
run "grep -E '^wheel|^sudo|^admin|^adm' /etc/group"
echo "@@SEC@@ U-12 계정이 존재하지 않는 GID 금지"
run "for g in \$(awk -F: '{print \$3}' /etc/group); do grep -q \":\$g:\" /etc/passwd || echo \"GID \$g 계정 없음\"; done"
echo "@@SEC@@ U-13 동일한 UID 금지"
run "awk -F: '{print \$3}' /etc/passwd | sort | uniq -d"
echo "@@SEC@@ U-14 사용자 shell 점검"
run "awk -F: '\$7 !~ /(false|nologin|sync|halt|shutdown)/ {print \$1, \$7}' /etc/passwd"
echo "@@SEC@@ U-15 Session Timeout 설정"
run "grep -rh '^TMOUT' /etc/profile /etc/profile.d/ /etc/bash.bashrc"
echo "@@SEC@@ U-16 root 홈, 패스 디렉터리 권한"
run "ls -ld /root"
echo "@@SEC@@ U-17 파일 및 디렉터리 소유자 설정"
run "find /etc /home /opt /srv /usr/local -xdev \( -nouser -o -nogroup \)"
echo "@@SEC@@ U-20 /etc/hosts 파일 소유자 및 권한"
run "ls -l /etc/hosts"
echo "@@SEC@@ U-21 (x)inetd.conf 파일 소유자 및 권한"
run "ls -l /etc/inetd.conf /etc/xinetd.conf"
echo "@@SEC@@ U-22 syslog 파일 소유자 및 권한"
run "ls -l /etc/rsyslog.conf"
run "systemctl is-active systemd-journald rsyslog"
run "journalctl --disk-usage"
run "ls -ld /var/log/journal"
echo "@@SEC@@ U-23 /etc/services 파일 소유자 및 권한"
run "ls -l /etc/services"
echo "@@SEC@@ U-24 SUID, SGID, Sticky bit 설정파일 점검"
run "find / -xdev -type f \( -perm -4000 -o -perm -2000 \)"
echo "@@SEC@@ U-25 시작/환경파일 소유자 및 권한"
run "ls -ld /etc/profile /etc/bash.bashrc /etc/skel /etc/rc.local /etc/init.d"
run "ls -l /etc/profile.d/"
echo "@@SEC@@ U-26 world writable 파일 점검"
run "find / -xdev -type f -perm -o+w | grep -v '^/proc\|^/sys\|^/run\|^/tmp\|^/var/tmp'"
echo "@@SEC@@ U-27 /dev device 파일 점검"
run "find /dev -xdev -type f"
echo "@@SEC@@ U-28 .rhosts, hosts.equiv 사용 금지"
run "ls -l /root/.rhosts /etc/hosts.equiv /home/*/.rhosts"
echo "@@SEC@@ U-29 접속 IP 및 포트 제한"
run "cat /etc/hosts.allow"
run "cat /etc/hosts.deny"
run "grep -iE '^listenaddress|^allowusers|^allowgroups|^denyusers' /etc/ssh/sshd_config"
echo "@@SEC@@ U-30 hosts.lpd 파일"
run "ls -l /etc/hosts.lpd"
echo "@@SEC@@ U-31 NIS / U-45 NIS+ 점검"
run "systemctl is-active nis ypbind"
run "dpkg -l | grep -iE '^(ii).*(ypbind|nis)' | grep -v libnss | grep -v unistring"
echo "@@SEC@@ U-32 UMASK 설정 관리"
run "grep -ri '^umask' /etc/profile /etc/profile.d/*.sh /etc/login.defs"
run "umask"
echo "@@SEC@@ U-33 홈 디렉터리 소유자 및 권한 / U-34 홈 존재"
run "ls -ld /home/*"
run "awk -F: '\$3>=1000 && \$3<65534 {print \$1, \$6}' /etc/passwd"
echo "@@SEC@@ U-35 숨겨진 파일 검색"
run "ls -la /home/kls/"
echo "@@SEC@@ U-36 Finger 서비스 비활성화"
run "systemctl is-active finger"
run "ss -tnl | grep ':79 '"
echo "@@SEC@@ U-37 Anonymous FTP 비활성화"
run "systemctl is-active vsftpd proftpd"
echo "@@SEC@@ U-38 r 계열 서비스 비활성화"
run "ss -tnl | grep -E ':513 |:514 '"
echo "@@SEC@@ U-39 cron 파일 소유자 및 권한"
run "ls -l /etc/crontab; ls -l /etc/cron.d/"
run "ls -ld /etc/cron.daily /etc/cron.hourly /etc/cron.weekly /etc/cron.monthly /var/spool/cron"
run "ls -l /var/spool/cron/crontabs/"
echo "@@SEC@@ U-40 DoS 취약 서비스 / U-46 tftp, talk"
run "ss -tnl | grep -E ':19 |:13 |:69 |:517 |:518 '"
echo "@@SEC@@ U-41 NFS 비활성화 / U-42 NFS 접근통제 / U-68 NFS 설정파일"
run "systemctl is-active nfs-server nfs-common rpcbind"
run "cat /etc/exports"
run "ss -tnl | grep ':2049 '"
echo "@@SEC@@ U-43 automountd 제거"
run "systemctl is-active autofs"
echo "@@SEC@@ U-44 RPC 서비스 확인"
run "ss -tnl | grep ':111 '"
run "rpcinfo -p localhost"
echo "@@SEC@@ U-47 Sendmail 버전 / U-48 릴레이 / U-49 실행 방지"
run "systemctl is-active sendmail postfix"
run "ls -l /usr/sbin/sendmail /usr/lib/sendmail"
run "dpkg -l | grep -E '^ii.*(postfix|sendmail|exim)'"
run "postconf -h inet_interfaces disable_vrfy_command"
echo "@@SEC@@ U-50 DNS 보안 버전 / U-51 Zone Transfer"
run "systemctl is-active named bind9"
run "ss -tnl | grep ':53 '"
echo "@@SEC@@ U-52~U-58 웹서버"
run "systemctl is-active apache2 nginx httpd lighttpd"
run "dpkg -l | grep -E '^ii.*(apache2|nginx)'"
run "ss -tnl | grep -E ':80 |:443 '"
echo "@@SEC@@ U-59 ssh 원격접속"
run "grep -iE '^protocol' /etc/ssh/sshd_config"
echo "@@SEC@@ U-60~U-63 FTP 서비스"
run "systemctl is-active vsftpd proftpd"
run "ls -l /etc/ftpusers"
run "cat /etc/ftpusers"
echo "@@SEC@@ U-64 at 서비스"
run "systemctl is-active atd"
run "ls -l /etc/at.deny /etc/at.allow /etc/cron.deny /etc/cron.allow"
echo "@@SEC@@ U-65 SNMP 구동 / U-66 Community"
run "systemctl is-active snmpd"
run "grep -v '^#' /etc/snmp/snmpd.conf | grep -v '^\$'"
echo "@@SEC@@ U-67 로그온 경고 메시지"
run "cat /etc/motd"
run "ls -l /etc/issue /etc/issue.net"
run "cat /etc/issue.net"
echo "@@SEC@@ U-69 expn, vrfy 제한"
run "grep -iE '^disable_vrfy_command|^smtpd_discard_ehlo' /etc/postfix/main.cf"
run "postconf disable_vrfy_command"
echo "@@SEC@@ U-70 Apache 정보 숨김"
run "systemctl is-active apache2 nginx"
run "dpkg -l | grep -cE '^ii.*(apache2|nginx)'"
echo "@@SEC@@ U-71 최신 보안패치"
run "cat /etc/debian_version"
run "uname -r"
run "apt list --upgradable | head -8"
run "apt list --upgradable | grep -c upgradable"
echo "@@SEC@@ U-72 로그 정기 검토"
run "systemctl is-active auditd logcheck"
run "ls /var/log/"
echo "@@SEC@@ U-73 시스템 로깅 설정"
run "grep -v '^#' /etc/systemd/journald.conf | grep -v '^\$'"
echo "@@DONE@@"
